import type { FaqItem } from "@/lib/content/types";

const FAQS: FaqItem[] = [
  { id: "1", category: "general", question: "Do I need a consultant, or can I apply on my own?", answer: "You can apply directly to IRCC without a consultant — the forms are public. But immigration law is complex, eligibility changes frequently, and a single mistake can mean refusals or delays. A regulated consultant helps you avoid costly errors and maximizes your chances of approval." },
  { id: "2", category: "general", question: "What's the difference between an RCIC and an immigration lawyer?", answer: "Both are authorized to provide immigration advice in Canada. RCICs specialize exclusively in immigration and are regulated by the CICC. Immigration lawyers are regulated by provincial law societies. For most immigration applications, an RCIC is fully qualified and often more cost-effective." },
  { id: "3", category: "general", question: "Are you authorized to represent me before IRCC?", answer: "Yes. As RCICs regulated by the CICC, we are authorized to prepare and submit immigration applications on your behalf and to communicate with IRCC for you." },
  { id: "4", category: "general", question: "What happens if my application is refused?", answer: "We review the refusal letter carefully and assess the grounds. Depending on the pathway, options may include reapplying with a stronger file, filing a reconsideration request, or appealing to the Immigration Appeal Division. We'll explain every option honestly." },
  { id: "5", category: "express-entry", question: "What is a CRS score and how is it calculated?", answer: "The Comprehensive Ranking System (CRS) assigns points based on age, education, language scores, work experience, and adaptability factors. The higher your score, the better your chances of receiving an Invitation to Apply (ITA) in a draw." },
  { id: "6", category: "express-entry", question: "How often does IRCC run Express Entry draws?", answer: "IRCC runs draws roughly every two weeks, though frequency and cut-off scores vary. Some draws target all candidates; others are category-specific (e.g. healthcare workers, STEM). We monitor draw patterns and advise clients accordingly." },
  { id: "7", category: "express-entry", question: "Can I improve my CRS score?", answer: "Often yes. Common strategies include retaking language tests, completing additional education, securing a provincial nomination, or obtaining a qualifying job offer. We assess your specific profile and identify the highest-impact improvements." },
  { id: "8", category: "pnp", question: "Which province is best for me?", answer: "It depends on your occupation, language skills, work or study history in Canada, and where you're willing to settle. Some provinces have streams specifically for tech workers, healthcare, agriculture, or entrepreneurs. We match your profile to streams with the best chance of success." },
  { id: "9", category: "pnp", question: "Do I need a job offer for PNP?", answer: "Not always. Many streams accept candidates without a job offer, particularly if you have relevant work experience or Canadian study credentials. Some streams do require a job offer — we'll clarify which apply to you." },
  { id: "10", category: "pnp", question: "Can PNP and Express Entry be combined?", answer: "Yes — this is called the Enhanced Nomination. A provincial nomination through an aligned stream adds 600 CRS points, putting candidates well above any recent Express Entry cutoff." },
  { id: "11", category: "family", question: "Who can I sponsor to come to Canada?", answer: "As a Canadian citizen or permanent resident, you can sponsor your spouse or common-law partner, dependent children, parents, and grandparents (subject to income requirements and intake caps)." },
  { id: "12", category: "family", question: "What is an undertaking and how long does it last?", answer: "An undertaking is a legal promise to financially support your sponsored family member and repay any social assistance they receive. For spouses and partners it lasts 3 years from PR; for parents and grandparents it lasts 20 years." },
  { id: "13", category: "family", question: "What if the relationship is questioned?", answer: "IRCC may request additional documentation or an interview to verify the genuineness of the relationship. We help you build a strong evidentiary file from the start to minimize this risk." },
  { id: "14", category: "work-study", question: "What is an LMIA and do I need one?", answer: "A Labour Market Impact Assessment (LMIA) is a document from Employment and Social Development Canada confirming that hiring a foreign worker won't negatively affect the Canadian labour market. Many work permits require one, but significant exemptions exist under CUSMA, IEC, and other agreements." },
  { id: "15", category: "work-study", question: "Can I work while studying in Canada?", answer: "Most full-time students at designated learning institutions (DLIs) can work up to 20 hours per week during the academic session and full-time during scheduled breaks, without a separate work permit." },
  { id: "16", category: "work-study", question: "What is a PGWP and how do I qualify?", answer: "A Post-Graduation Work Permit (PGWP) lets international graduates work in Canada for up to 3 years after completing a program of at least 8 months at an eligible DLI. It's one of the most direct pathways to Canadian PR for international students." },
  { id: "17", category: "process-fees", question: "Can you guarantee my application will be approved?", answer: "No — and you should be cautious of anyone who claims otherwise. IRCC makes all final decisions. What we can guarantee is that your application will be thorough, accurate, and presented in the strongest possible way. Our track record reflects that commitment." },
  { id: "18", category: "process-fees", question: "How much do your services cost?", answer: "Fees vary by pathway complexity and scope of service. We provide a clear, written quote after your free consultation — no hidden charges, no surprises. Government filing fees are separate and set by IRCC." },
];

export async function getFaqs(): Promise<FaqItem[]> {
  return FAQS;
}
